### PR TITLE
Branches and ports to Drupal 7, updates CFPropertyList

### PR DESCRIPTION
**Pull request by kylebrowning**
1. Branches and Ports to Drupal7
2. Updates CFPropertyList

### CODE REVIEW

**Comment by hugowetterberg** [comment]
Kyle, it's still not refactored into separate commits. If you take a look at my commits you have the message "Version 1.0.5 of cfpropertylist" when I included the cfpropertylist and "BigInteger.php from version 0.2.1 of phpseclib" when BigInteger was added. I want the update of the cfpropertylist library to be a similarly documented commit that is separate from the port to D7.

**Comment by kylebrowning** [comment]
Ahh, i see what you're saying. Ok im going to re-fork and do this that way, but itll be later today

**Comment by hugowetterberg** [comment]
Great, thanks!

**Comment by hugowetterberg** [comment]
No need to re-fork, just delete the 7.x-1.x branch from github

```
$ git push origin :7.x-1.x
```

Rename your local branch

```
$ git branch -m 7.x-1.x old-7.x-1.x
```

Reset master to its previous state

```
$ git checkout master
$ git reset --hard 63c5380048c3151d51c558fd225f5eb052a8ba41
```

Push the reset to github

```
$ git push --force origin master 
```

**Comment by hugowetterberg** [comment]
Tried to format the above comment so that it makes sense, but github hyperlinks the sha1, just use the long hex string instead of the a-tag.

**Pull request closed without merging**
